
<?php echo $this->getContent() ?>

<div align="right">
    <?php echo $this->tag->linkTo(array("items/new", "Create items")) ?>
</div>

<?php echo $this->tag->form(array("items/search", "autocomplete" => "off")) ?>

<div align="center">
    <h1>Search items</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="id">Id</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="type_id">Type</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("type_id", "type" => "number")) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Search") ?></td>
    </tr>
</table>

</form>
