<?php use Phalcon\Tag; ?>

<?php echo $this->getContent(); ?>

<table width="100%">
    <tr>
        <td align="left">
            <?php echo $this->tag->linkTo(array("items/index", "Go Back")); ?>
        </td>
        <td align="right">
            <?php echo $this->tag->linkTo(array("items/new", "Create ")); ?>
        </td>
    </tr>
</table>

<table class="browse" align="center">
    <thead>
        <tr>
            <th>Id</th>
            <th>Type</th>
         </tr>
    </thead>
    <tbody>
    <?php foreach ($page->items as $item) { ?>
        <tr>
            <td><?php echo $item->id ?></td>
            <td><?php echo $item->type_id ?></td>
            <td><?php echo $this->tag->linkTo(array("items/edit/" . $item->id, "Edit")); ?></td>
            <td><?php echo $this->tag->linkTo(array("items/delete/" . $item->id, "Delete")); ?></td>
        </tr>
    <?php } ?>
    </tbody>
    <tbody>
        <tr>
            <td colspan="2" align="right">
                <table align="center">
                    <tr>
                        <td><?php echo $this->tag->linkTo("items/search", "First") ?></td>
                        <td><?php echo $this->tag->linkTo("items/search?page=" . $page->before, "Previous") ?></td>
                        <td><?php echo $this->tag->linkTo("items/search?page=" . $page->next, "Next") ?></td>
                        <td><?php echo $this->tag->linkTo("items/search?page=" . $page->last, "Last") ?></td>
                        <td><?php echo $page->current, "/", $page->total_pages ?></td>
                    </tr>
                </table>
            </td>
        </tr>
    </tbody>
</table>
