
<?php echo $this->getContent() ?>

<div align="right">
    <?php echo $this->tag->linkTo(array("types/new", "Create types")) ?>
</div>

<?php echo $this->tag->form(array("types/search", "autocomplete" => "off")) ?>

<div align="center">
    <h1>Search types</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="id">Id</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="name">Name</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textArea(array("name", "cols" => 30, "rows" => 4)) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Search") ?></td>
    </tr>
</table>

</form>
